server:
  port: 8012
  servlet:
    context-path: /se
  error:
    path: /error

spring:
  datasource:
    username: root
    password: 6660590
    url: jdbc:mysql://localhost:3306/se?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  thymeleaf:
    mode: HTML5

